export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
  EMPLOYEE: 'EMPLOYEE'
};

export const EMPLOYEE_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ON_PIP: 'ON_PIP',
  TERMINATED: 'TERMINATED'
};

export const PERFORMANCE_LEVELS = {
  POOR: 'POOR',
  BELOW_AVERAGE: 'BELOW_AVERAGE',
  AVERAGE: 'AVERAGE',
  GOOD: 'GOOD',
  EXCELLENT: 'EXCELLENT'
};

export const PREDICTION_TYPES = {
  PERFORMANCE: 'PERFORMANCE',
  ATTRITION: 'ATTRITION',
  PRODUCTIVITY: 'PRODUCTIVITY',
  SKILL_GAP: 'SKILL_GAP'
};

export const APPROVAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

export const RISK_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

export const ETHICAL_RULE_TYPES = {
  BIAS_CHECK: 'BIAS_CHECK',
  THRESHOLD_VALIDATION: 'THRESHOLD_VALIDATION',
  SAFETY_CHECK: 'SAFETY_CHECK',
  FAIRNESS_CHECK: 'FAIRNESS_CHECK'
};

export const COURSE_STATUS = {
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

export const PIP_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  TERMINATED: 'TERMINATED'
};

export const PAGINATION_LIMIT = 10;
export const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
export const JWT_ACCESS_EXPIRE = '15m';
export const JWT_REFRESH_EXPIRE = '7d';
